// ids for window components

#define ID_TITLE_LABEL 89
#define ID_ADDWAVPATH 90
#define ID_ADDWAVPATH_LABEL 91

#define ID_PLAY_BUTTON 92
#define ID_STOP_BUTTON 94
#define ID_PAUSE_BUTTON 95
#define ID_DOWNLOAD_BUTTON 96
#define ID_PITCH_SHIFT_LABEL 99
#define ID_AUDIO_VISUALIZER 100
#define ID_FILE_DIALOG 101
#define ID_PITCH_SHIFT_SLIDER 102
#define ID_PITCH_SHIFT_SLIDER_LABEL 103
#define ID_CURR_STATE_LABEL 104
#define ID_LOWPASS_CHECKBOX 107
#define ID_KARAOKE_CHECKBOX 108
#define ID_HIGHPASS_CHECKBOX 113

#define ID_SPECIFY_SAMPLE_RATE_LABEL 97  
#define ID_SPECIFY_SAMPLE_RATE 98  
#define ID_SPECIFY_LOWPASS_CUTOFF_LABEL 109
#define ID_SPECIFY_LOWPASS_CUTOFF 110
#define ID_SPECIFY_HIGHPASS_CUTOFF_LABEL 111
#define ID_SPECIFY_HIGHPASS_CUTOFF 112

#define IDI_ICON 200