// ids for window components

#define ID_TITLE_LABEL 89
#define ID_ADDWAVPATH 90
#define ID_ADDWAVPATH_LABEL 91

#define ID_PLAY_BUTTON 92
#define ID_PLAY_KARAOKE_BUTTON 93
#define ID_STOP_BUTTON 94
#define ID_PAUSE_BUTTON 95 
#define ID_SAVE_KARAOKE 96
#define ID_PITCH_SHIFT 99
#define ID_AUDIO_VISUALIZER 100
#define ID_FILE_DIALOG 101

#define ID_SPECIFY_SAMPLE_RATE_LABEL 97  
#define ID_SPECIFY_SAMPLE_RATE 98  